In [2]:
import numpy as np

In [3]:
# 1D array
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
# 2D array
b=np.array([[1,2,3],
           [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

#### indexing

In [ ]:
a[0]

array([1, 2, 3])

In [7]:
a[2]

3

In [11]:
b[0,0]

1

In [12]:
b[1,2]

6

#### slicing

In [ ]:

a[:3]

array([1, 2, 3])

In [10]:
a[1:3]

array([2, 3])

#### mathematical operators

In [16]:
a + 5

array([ 6,  7,  8,  9, 10, 11])

In [17]:
a*2

array([ 2,  4,  6,  8, 10, 12])

In [18]:
np.sum(a)

21

In [19]:
np.mean(a)

3.5

In [20]:
np.max(a)

6

In [21]:
np.max(b)

6

In [25]:
arr=np.array([1,2,3])
arr2=np.array([4,5,6])
r=np.sum((arr,arr2))
r

21